In [2]:
import numpy as np

printing random numbers between one to hundred list of 5

In [7]:
x=np.random.randint(1,100,5)
x

array([61, 54, 65, 47, 77])

array creation

In [9]:
array = np.array([[1,3,7],[2,3,8],[10,29,6]])
array

array([[ 1,  3,  7],
       [ 2,  3,  8],
       [10, 29,  6]])

creating an array with range of value in ascending order

In [14]:
x= np.arange(1,10)
x

array([1, 3, 5, 7, 9])

 odd number between 0 to 100

In [17]:
a= np.arange(1,100,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

even number between 1 to 100

In [22]:
b=np.arange(2,100,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

printing array with zeros

In [23]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

printing array with ones

In [29]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

printing  array from zero to two with five evenly spaced values

In [33]:
arr = np.linspace(0,2,5)
arr

array([0. , 0.5, 1. , 1.5, 2. ])

In [36]:
array = np.random.rand(10)
array

array([0.9278142 , 0.04104415, 0.42878402, 0.43282865, 0.85700303,
       0.34196536, 0.09403221, 0.98311547, 0.55536187, 0.02776983])

finding maximum value,minimum value,median and mean value in a array

In [43]:
array = np.array([10,4,34,28,44,89,123,127,6,12,27,38,22])
max_value=np.max(array)
min_value=np.min(array)
median_value=np.median(array)
mean_value=np.mean(array)
print('maximum value',max_value)
print('minimum value ',min_value)
print('mean value',mean_value)
print('median value',median_value)

maximum value 127
minimum value  4
mean value 43.38461538461539
median value 28.0


printing dot product of two array

In [48]:
x=np.array([10,4,8])
y=np.array([7,6,3])
dot_product = np.dot(x,y)
print('dot product is',dot_product)


dot product is 118


In [49]:
x=np.array([6,4,8])
y=np.array([2,6,3])
cross_product=np.cross(x,y)

In [3]:
arr = np.array([4,10,2,6,8,12])
arr

array([ 4, 10,  2,  6,  8, 12])

In [4]:
np.append(arr,25)

array([ 4, 10,  2,  6,  8, 12, 25])

In [9]:
x=np.insert(arr,3,17)
x

array([ 4, 10,  2, 17,  6,  8, 12])

In [12]:
arr1=np.delete(x,3,axis=0)
arr1

array([ 4, 10,  2,  6,  8, 12])

scalar math

In [15]:
arr2=np.add(arr1,1)
arr2

array([ 5, 11,  3,  7,  9, 13])

In [18]:
arr3=np.subtract(arr2,2)
arr3

array([ 3,  9,  1,  5,  7, 11])

In [19]:
arr4=np.multiply(arr3,2)
arr4

array([ 6, 18,  2, 10, 14, 22])

In [20]:
arr5=np.divide(arr4,2)
arr5

array([ 3.,  9.,  1.,  5.,  7., 11.])

In [21]:
np.power(arr5,2)

array([  9.,  81.,   1.,  25.,  49., 121.])

vector math

In [22]:
arr1=np.array([24,21,3,8])
arr2=np.array([17,19,12,9])


In [23]:
np.add(arr1,arr2)

array([41, 40, 15, 17])

In [24]:
np.subtract(arr1,arr2)

array([ 7,  2, -9, -1])

In [25]:
np.multiply(arr1,arr2)

array([408, 399,  36,  72])

In [26]:
np.divide(arr1,arr2)

array([1.41176471, 1.10526316, 0.25      , 0.88888889])

In [29]:
np.power(arr2,arr1)

array([-830368383,  972113667,       1728,   43046721])

In [30]:
np.array_equal(arr1,arr2)

False

In [31]:
np.sqrt(arr1)

array([4.89897949, 4.58257569, 1.73205081, 2.82842712])

In [32]:
np.log(arr1)

array([3.17805383, 3.04452244, 1.09861229, 2.07944154])

In [33]:
np.abs(arr1)

array([24, 21,  3,  8])

In [34]:
np.corrcoef(arr1)

1.0